import type { NextPage } from "next";
import Head from "next/head";
import { Dishe, PageTemplate, Search } from "@/components";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>OnFood</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PageTemplate>
        <h1>Encontre opções em Delivery próximas á você.</h1>

        <Search />

        <h2>
          Descubra seu novo Delivery favorito. Milhares de opções a um clique.
        </h2>

        <Dishe /> 

      </PageTemplate>
    </>
  );
};

export default Home;
